name = "lyou-blog"
main = "worker.py"
compatibility_date = "2025-04-01"
compatibility_flags = ["python_workers"]

[[d1_databases]]
binding = "DB"
database_name = "lyou-blog-db"
database_id = "cecb23d5-c197-4b73-905d-f6c7407ce0d9"

[vars]
BLOG_ADMIN_USER = "admin"
